apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-01-03T16:07:13Z"
  generation: 1
  labels:
    app: doris
  name: doris
  namespace: default
  resourceVersion: "10299127"
  uid: 9b483f60-fea0-4a2e-9d7a-a65116849f9a
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: doris
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: doris
    spec:
      containers:
      - image: python
        imagePullPolicy: Always
        name: python
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
