apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ankeambom
  name: ankeambom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ankeambom
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ankeambom
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
